version: '1'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: instant-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
  front-chat:
    image: front-chat
    ports:
      - 3000:3000
    depends_on:
      - back-chat
  back-chat:
    image: back-chat
    ports:
      - 8080:8080
    depends_on:
      - postgres

    
    